### ISSUE TITLE
Consider "Vertical Slicing" over traditional "N-Tier" architecture.

### ISSUE THREAD

**Issue by beriniwlew** [Networked-Community/networked-community#14]
Large projects can get wildly in in a traditional n-tier layered architecture.   We should consider "[Vertical Slicing](https://www.kenneth-truyers.net/2016/02/02/vertical-slices-in-asp-net-mvc/)" instead.

The core ASP.NET Boilerplate solution will have to be restructured.

**Comment by hikalkan** [comment]
We implemented vertical slicing for pre-built application modules (https://github.com/abpframework/abp/tree/dev/modules)
We call it modularity, however. ABP Framework supports true modularity (https://docs.abp.io/en/abp/latest/Modules/Index).

**Comment by beriniwlew** [comment]
I think this issue is closed :)
