### ISSUE TITLE
Research Piranha CMS

### ISSUE THREAD

**Issue by beriniwlew** [Networked-Community/networked-community#33]
Let's take a look at Piranha's CMS.   It runs on dotnet core, so we can deploy this on multiple ecosystems.

https://github.com/PiranhaCMS

It looks very promising, and is more of a WYSIWYG editor.

**Comment by beriniwlew** [comment]
I don't think a WYSIWYG editor is appropriate - and may be too error prone.

**Comment by beriniwlew** [comment]
What do you think @villian ?

**Comment by villian** [comment]
Piranha CMS is a CMS that is headless, in the sense that it does not induce limitations or any HTML on you. Build your website in whatever way you want.

**Comment by beriniwlew** [comment]
What I really like about it is that it's lightweight.   

It also fits in nicely with our solution.
