### ISSUE TITLE
Research Open-Source alternatives to Slack

### ISSUE THREAD

**Issue by beriniwlew** [Networked-Community/networked-community#40]
Slack is a wonderful tool, but it would be nice to not be tied to it and have our own system to work under, which would be more private.

**Comment by WeaverHeavy** [comment]
@beriniwlew @marvinroman @jpb5013  Check out: https://github.com/mattermost/mattermost-server

I use this professionally with other organizations to great effect. You can easily spin up an environment with docker compose also.

**Comment by beriniwlew** [comment]
@WeaverHeavy thanks for pointing us in the right direction!
